Repository ILLIXR/ILLIXR, pull requests merged in 2020-11, with the labels that each got.

#155 Issue 122 timewarp
  common/threadloop.hpp
  timewarp_gl/plugin.cpp
Labels: feature

#165 Update docs for the new runner
  docs/debugging_illixr.md
  docs/modifying_a_plugin.md
  docs/writing_your_plugin.md
  mkdocs.yml
Labels: documentation

#169 Fix broken links in docs
  docs/debugging_illixr.md
  docs/modifying_a_plugin.md
  docs/writing_your_plugin.md
Labels: bug

#174 Don't make GL context current in runtime thread
  common/extended_window.hpp
Labels: bug

#140 OV Integrator (Fix MTP)
  configs/rt_slam_plugins.yaml
  gtsam_integrator/plugin.cpp
  offline_imu_cam/plugin.cpp
  rk4_integrator/CMakeLists.txt
  rk4_integrator/Makefile
  rk4_integrator/plugin.cpp
  zed/src/main.cpp
Labels: bug, feature, plumbing

#178 Fixed pose_lookup, plus renamed config to native-lookup
  configs/native-lookup.yaml
  pose_lookup/plugin.cpp
Labels: bug

#195 Fix runner for monado
  configs/rt_slam_plugins.yaml
  runner/runner/main.py
Labels: bug, good first issue, infrastructure
