Repository ILLIXR/ILLIXR, pull requests merged in 2020-09, with the labels that each got.

#64 Kill subprocesses on failure
  runner/runner/main.py
Labels: WIP

#99 Download EuRoC in install_deps
  install_deps.sh
  scripts/install_euroc.sh
Labels: bug

#109 Switchboard blocks instead of spinning on queue
  runtime/concurrentqueue/README.txt
  runtime/concurrentqueue/blockingconcurrentqueue.hpp
  runtime/concurrentqueue/concurrentqueue.hpp
  runtime/concurrentqueue/lightweightsemaphore.hpp
  runtime/runtime_impl.hpp
  runtime/switchboard_impl.hpp
Labels: perf-improvement

#102 Sqlite Logging implementation
  common/record_logger.hpp
  runtime/concurrentqueue.hpp
  runtime/runtime_impl.hpp
  runtime/sqlite3pp/README.txt
  runtime/sqlite3pp/sqlite3pp.hpp
  runtime/sqlite3pp/sqlite3pp_interface.hpp
  runtime/sqlite_record_logger.hpp
Labels: feature

#116 Implement MTP
  common/shader_util.hpp
  debugview/plugin.cpp
  gldemo/plugin.cpp
  pose_prediction/plugin.cpp
  timewarp_gl/plugin.cpp
Labels: feature

#131 ILLIXR-Monado doesn't work on a fresh 20.04 build
  Dockerfile
  scripts/install_apt_deps.sh
Labels: bug

#119 Fix Monado build with runner
  configs/monado.yaml
  runner/runner/main.py
Labels: bug, good first issue

#130 Timewarp doesn't sync with the application correctly
  timewarp_gl/plugin.cpp
Labels: bug

#135 Add badges/status icons to README
  README.md
Labels: documentation, feature

#123 Complete removal of ksAlgebra + timewarp improvements
  common/math_util.hpp
  debugview/plugin.cpp
  debugview/utils/algebra.cpp
  debugview/utils/algebra.hpp
  gldemo/plugin.cpp
  gldemo/utils/algebra.cpp
  gldemo/utils/algebra.hpp
  timewarp_gl/plugin.cpp
  timewarp_gl/shaders/timewarp_shader.hpp
  timewarp_gl/utils/algebra.cpp
  timewarp_gl/utils/algebra.hpp
Labels: design decision, documentation

#127 Remove legacy frame format (rename "rendered_frame_alt")
  common/data_format.hpp
  gldemo/plugin.cpp
  timewarp_gl/plugin.cpp
Labels: design decision, plumbing
