Repository ILLIXR/ILLIXR, pull requests merged in 2021-04, with the labels that each got.

#258 Add KIMERA_ROOT for default monado config, update runner
  CONTRIBUTORS
  configs/monado.yaml
  runner/runner/main.py
Labels: bug, infrastructure, plumbing

#261 Hotfix: Added Git tags for `monado_integration` and fixed `clean` for `configs/clean.yaml`
  common/common.mk
  configs/clean.yaml
  configs/monado.yaml
Labels: bug, infrastructure

#266 Feature: Offloaded SLAM
  configs/core_plugins.yaml
  configs/native.yaml
  mxre_reader/plugin.cpp
  mxre_writer/plugin.cpp
  pose_prediction/plugin.cpp
Labels: feature

#272 Updated `README.md` to match `illixr.github.io`
  README.md
Labels: documentation

#32 Use ref-counting in Switchboard (patch memory leak)
  common/common.mk
  common/data_format.hpp
  common/extended_window.hpp
  common/global_module_defs.hpp
  common/managed_thread.hpp
  common/plugin.hpp
  common/record_logger.hpp
  common/switchboard.hpp
  common/tests/test_switchboard.cpp
  configs/ci.yaml
  configs/clean.yaml
  configs/core_plugins.yaml
  configs/docs.yaml
  configs/headless.yaml
  configs/monado.yaml
  configs/native-lookup.yaml
  configs/native.yaml
  configs/rt_slam_plugins.yaml
  debugview/plugin.cpp
  doxygen.conf
  gldemo/plugin.cpp
  ground_truth_slam/plugin.cpp
  gtsam_integrator/plugin.cpp
  offline_imu_cam/plugin.cpp
  offload_data/plugin.cpp
  pose_lookup/data_loading.hpp
  pose_lookup/plugin.cpp
  pose_lookup/utils.hpp
  pose_prediction/plugin.cpp
  realsense/plugin.cpp
  rk4_integrator/plugin.cpp
  runner/config_schema.yaml
  runner/runner/main.py
  runner/runner/util.py
  runtime/main.cpp
  runtime/runtime_impl.hpp
  runtime/sqlite_record_logger.hpp
  runtime/switchboard_impl.hpp
  scripts/install_gtsam.sh
  timewarp_gl/plugin.cpp
  zed/CMakeLists.txt
  zed/common
  zed/src/main.cpp
Labels: WIP, bug

#278 Fix `headless.yaml` command argument
  CONTRIBUTORS
  configs/headless.yaml
Labels: bug

#249 Add stoplight to synchronize thread starts/stops
  common/plugin.hpp
  common/runtime.hpp
  common/stoplight.hpp
  common/threadloop.hpp
  docs/writing_your_plugin.md
  runtime/runtime_impl.hpp
Labels: design decision, feature

#269 Expand `realsense` supported cameras
  configs/monado.yaml
  configs/native.yaml
  configs/rt_slam_plugins.yaml
  realsense/plugin.cpp
  runner/config_schema.yaml
  runner/runner/main.py
Labels: feature

#248 Updated contributing guidelines
  CONTRIBUTING.md
  docs/CONTRIBUTING.md
  docs/getting_started.md
  mkdocs.yml
Labels: design decision, documentation
