Repository ILLIXR/ILLIXR, pull requests merged in 2021-03, with the labels that each got.

#237 Fixed code block rendering and highlighting in docs
  CONTRIBUTING.md
  configs/docs.yaml
  docs/building_illixr.md
  docs/getting_started.md
  docs/modifying_a_plugin.md
  docs/writing_your_plugin.md
Labels: bug, documentation

#238 Fixed README internal links
  README.md
Labels: bug, documentation

#189 Update Plugin Docs for up to date topic information
  docs/dataflow.dot
  docs/dataflow.dot.png
  docs/debugging_illixr.md
  docs/illixr_plugins.md
  docs/images
  docs/images/1-install-en.png
  docs/images/2-erase-all.png
  docs/images/3-continue.png
  docs/images/4-done.png
  docs/images/dataflow.dot.png
  timewarp_gl/plugin.cpp
Labels: documentation

#243 Deployed 0e6901b936 with MkDocs version: 1.1.2
  api/html/data__format_8hpp_source.html
  api/html/global__module__defs_8hpp_source.html
  building_illixr/index.html
  debugging_illixr/index.html
  getting_started/index.html
  illixr_plugins/index.html
  index.html
  modifying_a_plugin/index.html
  search/search_index.json
  sitemap.xml
  writing_your_plugin/index.html
Labels: documentation

#242 Fixed gtsam, opengv, and Eigen installation
  Dockerfile
  install_deps.sh
  scripts/bash_utils.sh
  scripts/default_values.sh
  scripts/install_apt_deps.sh
  scripts/install_eigen.sh
  scripts/install_gtsam.sh
  scripts/install_opengv.sh
  scripts/system_utils.sh
Labels: bug, infrastructure

#227 Issue 225 error checking
  common/common.mk
  common/cpu_timer.hpp
  common/data_format.hpp
  common/dynamic_lib.hpp
  common/error_util.hpp
  common/extended_window.hpp
  common/gl_util/obj.hpp
  common/global_module_defs.hpp
  common/shader_util.hpp
  common/threadloop.hpp
  configs/ci.yaml
  configs/clean.yaml
  configs/core_plugins.yaml
  configs/docs.yaml
  configs/headless.yaml
  configs/monado.yaml
  configs/native-lookup.yaml
  configs/native.yaml
  configs/rt_slam_plugins.yaml
  debugview/plugin.cpp
  gldemo/Makefile
  gldemo/plugin.cpp
  ground_truth_slam/data_loading.hpp
  gtsam_integrator/plugin.cpp
  offline_imu_cam/data_loading.hpp
  offline_imu_cam/plugin.cpp
  offload_data/plugin.cpp
  pose_lookup/plugin.cpp
  rk4_integrator/plugin.cpp
  runner/config_schema.yaml
  runner/runner/main.py
  runner/runner/util.py
  runtime/main.cpp
  runtime/runtime_impl.hpp
  runtime/sqlite_record_logger.hpp
  runtime/switchboard_impl.hpp
  timewarp_gl/Makefile
  timewarp_gl/plugin.cpp
  zed/src/main.cpp
Labels: bug

#252 Hotfix: GL performance warnings are no longer fatal
  common/shader_util.hpp
  debugview/plugin.cpp
  gldemo/plugin.cpp
  timewarp_gl/plugin.cpp
Labels: bug

#254 Fixed multiple definitions in global helper functions
  common/global_module_defs.hpp
Labels: bug
